"""empty message

Revision ID: 43990748dc56
Revises: 
Create Date: 2023-01-18 20:54:39.016085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43990748dc56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('age', sa.String(), nullable=True),
    sa.Column('attendance', sa.String(), nullable=True),
    sa.Column('score', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('school')
    # ### end Alembic commands ###
